### ISSUE TITLE
RSS Compatibility

### ISSUE THREAD

**Issue by Kalmorph** [linuxgurugamer/WaypointManager#11]
Playing the mod with RP-1, it keeps reverting all changes and reseting after changing scenes.

**Comment by linuxgurugamer** [comment]
Which changes are being reverted?  A log file would be useful

**Comment by Kalmorph** [comment]
Sorry if my details may be off, I don't play the game since December.

If I remember correctly, using the mod with RP-1 would start with dozens of different waypoints with the same coordinates and in the sun. I figured the mod was trying to add waypoints for the vanilla KSP, but since the planets didn't existed on RSS, it was putting in the sun instead, or something like that. So I deleted all the initial waypoints and created a new one, but it would get reset back to how it started, with all dozens of waypoints and none of the ones I created.

I can't provide a log at all, I don't even have KSP installed anymore. All I can tell is how to reproduce, which wasn't that much a chore, I just used the express install on CKAN to get RP-1 and your mod from there.
In-game, just make anything at all to launch go on-mission, open the map and the waypoints list may be all showing things on the sun, and deleting or changing anything and returning the vessel, it would just be the same when launching another one.

**Comment by Clayell** [comment]
Can confirm that the dozens of waypoints on the sun bug with RSS is pretty common. This is a screenshot from someone else on the RP-1 server, but I also see this myself everytime I use waypoint manager.

![Image](https://github.com/user-attachments/assets/3827f5ad-178f-4a8d-95d2-214209c9a079)


~~Is it possible that the [custom waypoints](https://github.com/linuxgurugamer/WaypointManager/tree/master/GameData/WaypointManager/PluginData/CustomWaypoints) are getting loaded for RSS systems?~~ (don't think so, I deleted all of my custom waypoints files and these waypoints still showed up)

There is a reference to the KSC waypoint in https://github.com/jrossignol/WaypointManager/issues/59.

**Comment by Clayell** [comment]
![Image](https://github.com/user-attachments/assets/3a328b10-a035-40c0-9fea-8965288e8bb0)
This bug appears with a fresh install of RP-1 express and Waypoint Manager.
Additionally, I may have found error logs in KSP.log and Player.log relating to this bug:
> [WRN 19:55:18.703] Contract Log: ScenarioCustomWaypoints cannot load navigationId, it is not in the node. Initializing with default of c7900bcd-0981-4014-86a9-ed6d833f59a3!

KSP.log: https://drive.google.com/file/d/1UK3nuK-VP9nnANEjt40Aj3Hf30r0sB4f/view?usp=sharing
Player.log: https://drive.google.com/file/d/1hQLB1s1U_keOtGI4Iz74XJod7yqvQMia/view?usp=sharing

Deleting any of these waypoints, changing to a different scene, and then opening the waypoint manager up again causes the waypoints to regenerate. The icon that the "Site" waypoints have is also very strange, and not seen anywhere else I believe.

![Image](https://github.com/user-attachments/assets/a162fa63-56dd-48d0-a797-9ed435adfc65)

**Comment by Clayell** [comment]
Hm, this is strange. Having only RSS installed, I only got the sun KSC waypoint, not the other "Site" waypoints.

![Image](https://github.com/user-attachments/assets/c12113ae-a9af-48f3-875e-12afd490d8e7)

Installed Mods: (also Principia)
```
ClickThrough Blocker (ClickThroughBlocker 1:2.1.10.22)
Harmony 2 (Harmony2 2.2.1.0)
Kopernicus Planetary System Modifier (Kopernicus 2:release-1.12.1-223)
KSP Community Fixes (KSPCommunityFixes 1.36.1)
ModularFlightIntegrator (ModularFlightIntegrator 1.2.10.0)
Module Manager (ModuleManager 4.2.3)
Notes2Log (Notes2Log 0.0.3.3)
QuickGoTo (QuickGoTo 1:1.4.0.11)
QuickMute (QuickMute 1:1.4.0.9)
Real Solar System (RealSolarSystem v20.1.3.0)
Real Solar System Textures - 16384 x 8192 (RSSTextures16K v18.6.1)
SpaceTux Library (SpaceTuxLibrary 0.0.8.7)
Toolbar Controller (ToolbarController 1:0.1.9.11)
WaypointManager (WaypointManager 2.8.4.5)
```

I used Notes2Log to make some notes on when I was performing actions. I typed "removing ksc for a 2nd time now" right before I removed the KSC waypoint. I then went out of the tracking station scene, and re-entered it. I then typed "back in tracking station, ksc regenerated". I have noticed several hundreds of lines of errors between these points, from 17:04:10 to 17:04:32, which is worrying.
KSP.log: https://drive.google.com/file/d/1wv80qNvmcfsvpXdw2mgugQyTryPXuGN9/view?usp=sharing
Player.log: https://drive.google.com/file/d/1qdfwvFkAeNXiDjraDWJ_ubMA5nIGF11A/view?usp=sharing

I will try to track down which mod triggers the "Site" waypoints.

**Comment by Clayell** [comment]
After 2 hours of sifting through mods, I have finally discovered that Real Antennas is the source behind all of those "Site" waypoints. I believe this is due to the custom ground stations it adds, but I'm not sure.

> Clayel: can someone confirm that realantenna adds waypoints at some point?
DRVeyl (creator of RealAntennas): No? It adds sites, like all of the stock ground stations have.

![Image](https://github.com/user-attachments/assets/41fb920f-8801-40e4-a95a-7b7d77bcd1be)

Installed Mods: (also Principia)
```
ClickThrough Blocker (ClickThroughBlocker 1:2.1.10.22)
Harmony 2 (Harmony2 2.2.1.0)
Kopernicus Planetary System Modifier (Kopernicus 2:release-1.12.1-223)
KSP Community Fixes (KSPCommunityFixes 1.36.1)
KSPBurst (KSPBurst v1.5.5.1)
ModularFlightIntegrator (ModularFlightIntegrator 1.2.10.0)
Module Manager (ModuleManager 4.2.3)
Notes2Log (Notes2Log 0.0.3.3)
QuickGoTo (QuickGoTo 1:1.4.0.11)
QuickMute (QuickMute 1:1.4.0.9)
Real Antennas (RealAntennas v2.8.0.0)
Real Solar System (RealSolarSystem v20.1.3.0)
Real Solar System Textures - 16384 x 8192 (RSSTextures16K v18.6.1)
SpaceTux Library (SpaceTuxLibrary 0.0.8.7)
Toolbar Controller (ToolbarController 1:0.1.9.11)
WaypointManager (WaypointManager 2.8.4.5)
```

Here's something else quite interesting. In the pictures below, we can see that both the "KSC" and "Site" waypoints fail the [IsCustom](https://github.com/linuxgurugamer/WaypointManager/blob/07d3f9d3c129c29d897eccfb62c1a637e4d3538b/WaypointManager/WaypointManager.cs#L461-L494) check, so the game is considering them to actually be stock waypoints instead of a custom waypoints.

![Image](https://github.com/user-attachments/assets/b40a521e-4beb-4d19-bacf-d0f5c5cb8e76)

![Image](https://github.com/user-attachments/assets/56f56a6b-d65a-46e1-8171-7149ad51de84)

Here are my logs below, I left the following notes through Notes2Log (very useful mod btw) for the actions I took:
- "in tracking station for first time" when in the tracking station and having the waypoint manager open
- "have now deleted ksc waypoint" after only deleting the KSC waypoint
- "have now deleted all waypoints, exiting tracking station now" after deleting all of the other waypoints and before exiting the tracking station
- "outside of tracking station now" in the KSC scene after exiting the tracking station
- "re-entered tracking station, all waypoints have returned" after re-entering the tracking station and opening the waypoint manager

KSP.log: https://drive.google.com/file/d/1ai5s2fA2G490pCQBp3I-cvl91Cr5FSqa/view?usp=sharing
Player.log: https://drive.google.com/file/d/1w1VvcL6HqYkkt41XfXQf3rrD4wYxMiW-/view?usp=sharing

**Comment by linuxgurugamer** [comment]
I took a look at those log files.  The NullRef is not even in this mod, it's inside the game itself.  Looks like Waypoint.node is a MapNode and that's not initialized.
I'm curious, if RealAntennas is NOT installed, do those errors occur?

Edit:  I've been able to reproduce the problem on a vanilla RP-1 install.  Interestingly enough, when I installed RealAntennas on a stock game, there wasn't any problem.  So there is some sort of interaction between what is installed with RP1, RealAntennas and Waypoint Manager causing the issue

**Comment by linuxgurugamer** [comment]
I installed Real Antennas on a stock install (both with and without Kopernicus).  No errors were seen, but when I went into flight I saw a 13 waypoints on the Sun at coordinates Lat 0,0,0   Lon 0,0,0

I suspect that's where the problem is coming from.  Someone (maybe me) will have to look at Real Antennas and see what it's doing, there shouldn't be this at all:

![Image](https://github.com/user-attachments/assets/36d63d87-62d8-4321-8d69-575f9df1b98f)

I traced this to the file RealAntennas/PlanetPacks/Stock.cfg.  Removing this file eliminated all those 13 Sun waypoints, although I'm not sure what's going on yet, that file is needed by Kopernicus, not sure why it's being used when I do not have Kopernicus installed in the stock game.  Next step is to remove it from the RP-1 and see what happens

(deleted error messages about Telecom.dll, not relevant)

I am beginning to think this isn't a bug in WaypointManager, but rather WaypointManager is exposing a bug in another mod.   Simply removing the new waypoint definitions from RealAntennas shouldn't cause errors, and also, having all those Sun locations in a stock game is concerning.  Something is not being initialized properly, but I don't think it's this mod 

It may even be in Kopernicus

**Comment by Clayell** [comment]
It must be a very strange interaction to only show up when waypoint manager is installed, especially since waypoint manager doesn't seem to automatically place any waypoints down. DRVeyl told me that RA "adds sites, like all of the stock ground stations have", but doesn't add any waypoints.

By "stock install", do you mean that you installed real antennas without real solar system, and there were still waypoints placed on the sun?

Asides from the waypoints that RA causes, the bugged "KSC" waypoint is from the same bug mentioned in https://github.com/jrossignol/WaypointManager/issues/59, right?

Let me know what I can do to help your testing.

**Comment by linuxgurugamer** [comment]
Waypoint manager is probably calling something in KSP which nothing else does, and that's triggering the issue
I'll look, but this isn't a high priority for me right now, working on other mods

**Comment by linuxgurugamer** [comment]
I'll leave this open, but have been able to confirm that (probably) Kopernicus is not adding the PQS  nodes into KSP.

The node I tested with is:
`			PQS
			{
				Mods
				{
					City2
					{
						name = LaunchSiteTrackingStation
						objectName = Woomerang Station
						isKSC = True
						lat = 45.29
						lon = 136.12
						alt = 777
						enabled = True
						snapToSurface = True
						snapHeightOffset = 0
						up = 0.0, 1.0, 0.0
						rotation = 0
						order = 100
						enabled = True
						commnetStation = False
						RACommNetStation = True
						icon = RealAntennas/radio-antenna
						LOD
						{
							Value
							{
								visibleRange = 30000
								keepActive = False
								model = BUILTIN/Dish
								scale = 0.1, 0.1, 0.1
								delete = False
							}
						}
						Antenna
						{
							referenceGain = 1.5
							referenceFrequency = 1620
							TxPower = 40
							TechLevel = 0
							RFBand = L
							AMWTemp = 290
							ModulationBits = 1
						}
					}
				}
			}

`

I then dumped the data from FinePrint.WaypointManager, and got the following:
`74032 WaypointManager: WorldPosition: [0, 0, 0] 
74035 WaypointManager: orbitPosition: (0.0, 0.0, 0.0) 
74038 WaypointManager: name: Site, latitude: 0, longitude: 0, Altitude: 0 
`
I'll open a ticket in Kopernicus

**Comment by linuxgurugamer** [comment]
@Clayell I'm taking a stab at it.  Going on the assumption that those City2 locations are NOT meant to be waypoint, I've added a filter it ignore lines which are invalid.

Please try this and let me know how it goes:

[WaypointManager.zip](https://github.com/user-attachments/files/19235871/WaypointManager.zip)

**Comment by linuxgurugamer** [comment]
> ![Image](https://github.com/user-attachments/assets/3a328b10-a035-40c0-9fea-8965288e8bb0) This bug appears with a fresh install of RP-1 express and Waypoint Manager. Additionally, I may have found error logs in KSP.log and Player.log relating to this bug:
> 
> > [WRN 19:55:18.703] Contract Log: ScenarioCustomWaypoints cannot load navigationId, it is not in the node. Initializing with default of c7900bcd-0981-4014-86a9-ed6d833f59a3!

That may be caused by bad data created by earlier problems related to this issue

**Comment by Clayell** [comment]
![Image](https://github.com/user-attachments/assets/ba9012fe-c603-4364-ae57-f4ac436df2c5)
Your dll seems to remove all of the faulty waypoints (except the still-bugged KSC waypoint).

Logs: (don't seem to have any errors, well at least any containing "Waypoint" in the name)
KSP.log: https://drive.google.com/file/d/1YAvY_WMPewy8hPfbj4b8yKuxBQZy1baW/view?usp=sharing
Player.log: https://drive.google.com/file/d/1vUW_ckxJehvZLg3QUxOHpUDLf5qPupPt/view?usp=sharing

Modlist: (also Principia)
```
Advanced Jet Engine (AdvancedJetEngine v2.20.0)
AlphaMensae's Modular Launch Pads (ModularLaunchPads 2.8.0)
AtmosphereAutopilot (Fly-By-Wire) (AtmosphereAutopilot v1.6.1)
B9 Aerospace Procedural Wings - Fork (B9-PWings-Fork 3:0.46.0)
B9 Part Switch (B9PartSwitch v2.20.0)
BahamutoD Animation Modules (BDAnimationModules 1:v0.6.7.1)
CanaveralPads (CanaveralPads v1.1.0.0)
ClickThrough Blocker (ClickThroughBlocker 1:2.1.10.22)
Community Category Kit (CommunityCategoryKit v112.0.1)
Community Resource Pack (CommunityResourcePack v112.0.1)
Conformal Decals (ConformalDecals 0.2.14)
Contract Configurator (ContractConfigurator v2.11.1.0)
Custom Barn Kit (CustomBarnKit 1.1.22.0)
Custom Pre Launch Checks (CustomPreLaunchChecks 1.8.1.1)
Deferred (Deferred 1.2.6.0)
Distant Object Enhancement /L (DistantObject v2.2.0.2)
Distant Object Enhancement /L default config (DistantObject-default v2.2.0.2)
Editor Extensions Redux (EditorExtensionsRedux 3.4.6.1)
Environmental Visual Enhancements Redux (EnvironmentalVisualEnhancements 3:1.11.7.2)
Express Install Realism Overhaul/Realistic Progression 1 (RO/RP-1) (RP-1-ExpressInstall v2.0)
Ferram Aerospace Research Continued (FerramAerospaceResearchContinued 3:0.16.1.2)
Firespitter Core (FirespitterCore v7.17)
Firespitter Resources config (FirespitterResourcesConfig v7.17)
Hangar Extender (HangerExtenderExtended 3.6.0.2)
Harmony 2 (Harmony2 2.2.1.0)
High Graphics (RP-1-ExpressInstall-Graphics-High v1.0.0.0)
Kerbal Alarm Clock (KerbalAlarmClock v3.14.0.0)
Kerbal Changelog (KerbalChangelog v1.4.2)
Kerbal Foundries2 (KerbalFoundriesContinued 2.4.8.18)
Kerbal Joint Reinforcement Continued (KerbalJointReinforcementContinued v3.8.4.0)
Kerbal Konstructs (KerbalKonstructs v1.8.10.0)
Kerbal Renamer (KerbalRenamer v1.7.0.0)
Kerbalism (Kerbalism 3.19)
Kerbalism - RealismOverhaul Config (Kerbalism-Config-RO v1.3.1.0)
Kopernicus Planetary System Modifier (Kopernicus 2:release-1.12.1-223)
KSC Extended (KSCExtended 3.0.3)
KSC Switcher (KSCSwitcher v2.2.0.0)
KSP Community Fixes (KSPCommunityFixes 1.36.1)
KSP Resonant Orbit Calculator (ResonantOrbitCalculator 0.0.7)
KSP Wheel (KSPWheel 1:0.16.14.33)
KSPBurst (KSPBurst v1.5.5.1)
Lunar Transfer Planner (LunarTransferPlanner v1.0.0)
MechJeb 2 (MechJeb2 2.14.3.0)
ModularFlightIntegrator (ModularFlightIntegrator 1.2.10.0)
Module Manager (ModuleManager 4.2.3)
ModuleDepthMask (DepthMask 1.1.3)
Notes2Log (Notes2Log 0.0.3.4)
Omega's Stockalike Structures: No Textures Required (StockalikeStructures 0.0.12)
Parallax (Parallax 2.0.8)
Parallax - Stock Planet Textures (Parallax-StockTextures 2.0.8)
Parallax - Stock Scatter Textures (Parallax-StockScatterTextures 2.0.8)
Patch Manager (PatchManager 0.0.17.6)
PlanetShine (PlanetShine 0.2.6.6)
PlanetShine - Default configuration (PlanetShine-Config-Default 0.2.6.6)
Procedural Fairings (ProceduralFairings 1:v6.6.2.0)
Procedural Parts (ProceduralParts v2.7.2.0)
QuickGoTo (QuickGoTo 1:1.4.0.11)
QuickMute (QuickMute 1:1.4.0.9)
RCS Build Aid (RCSBuildAid v1.0.6)
Real Antennas (RealAntennas v2.8.0.0)
Real Fuels (RealFuels 1:v15.11.1.0)
Real Plume (RealPlume 2:v13.3.2)
Real Solar System (RealSolarSystem v20.1.3.0)
Real Solar System Textures - 16384 x 8192 (RSSTextures16K v18.6.1)
RealChute for Stock (RealChuteForStock v1.4.9.5)
RealChute Parachute Systems (RealChute v1.4.9.5)
RealHeat (RealHeat v5.1)
Realism Overhaul (RealismOverhaul v17.17.0.0)
Realistic Progression One (RP-1) (RP-1 v3.19.0.0)
ReStock (ReStock 1.5.1)
ReStock+ (ReStockPlus 1.5.1)
Resurfaced (Resurfaced v1.2)
Retractable Lifting Surface Module (RetractableLiftingSurface 0.2.1.2)
RO Capsules (ROCapsules v2.6.1.0)
RO Engines (ROEngines v2.13.0.0)
RO Heatshields (ROHeatshields v1.3.0.0)
RO Library (ROLib v1.9.1.0)
RO Solar (ROSolar v2.1.2.0)
RO Tanks (ROTanks v2.10.0.0)
ROLoadingImages (ROLoadingImages v1.0.0.0)
ROUtils (ROUtils v1.0.1.0)
RSS CanaveralHD (RSS-CanaveralHD v1.0.1)
RSS DateTime Formatter (RSSDateTimeFormatter v1.12.1.0)
RSS Visual Enhancements - High Resolution (RSSVE-HR v2.2.1)
Scatterer (Scatterer 3:v0.0878)
Scatterer Default Config (Scatterer-config 3:v0.0878)
Scatterer Sunflare (Scatterer-sunflare 3:v0.0878)
Shabby (Shabby 0.4.0)
Shaddy (Shaddy v2.5)
SmokeScreen - Extended FX Plugin (SmokeScreen 2.8.14.0)
Solver Engines plugin (SolverEngines v3.14.0)
SpaceTux Library (SpaceTuxLibrary 0.0.8.7)
Staged Animation (StagedAnimation v2.0)
SXTContinued (SXTContinued 2:0.3.29.9)
Test Flight (TestFlight v2.9.0.0)
TextureReplacer (TextureReplacer v4.5.3)
Textures Unlimited (TexturesUnlimited 1.6.3.29)
Toolbar Controller (ToolbarController 1:0.1.9.11)
Transfer Window Planner - Fork (TransferWindowPlannerFork v1.9.1.0)
Tundra's Space Center (TundraSpaceCenter 2.0.2)
TweakScale Redistributable (TweakScale-Redist v2.4.8.6)
Ven's New Parts (VenStockRevamp-NewParts v1.16.0)
Ven's Stock Part Revamp Core (VenStockRevamp-Core v1.16.0)
Waterfall Core (Waterfall 0.10.3)
WaypointManager (WaypointManager 2.8.4.5)
Σκοπός (Skopos v1.0.1.0)
```

**Comment by linuxgurugamer** [comment]
> ![Image](https://github.com/user-attachments/assets/ba9012fe-c603-4364-ae57-f4ac436df2c5) Your dll seems to remove all of the faulty waypoints (except the still-bugged KSC waypoint).
> 
> Logs: (don't seem to have any errors, well at least any containing "Waypoint" in the name) KSP.log: https://drive.google.com/file/d/1YAvY_WMPewy8hPfbj4b8yKuxBQZy1baW/view?usp=sharing Player.log: https://drive.google.com/file/d/1vUW_ckxJehvZLg3QUxOHpUDLf5qPupPt/view?usp=sharing
> 
 ```

What about the original problem, where it loses waypoints?

**Comment by linuxgurugamer** [comment]
> > ![Image](https://github.com/user-attachments/assets/ba9012fe-c603-4364-ae57-f4ac436df2c5) Your dll seems to remove all of the faulty waypoints (except the still-bugged KSC waypoint).
> > Logs: (don't seem to have any errors, well at least any containing "Waypoint" in the name) KSP.log: https://drive.google.com/file/d/1YAvY_WMPewy8hPfbj4b8yKuxBQZy1baW/view?usp=sharing Player.log: https://drive.google.com/file/d/1vUW_ckxJehvZLg3QUxOHpUDLf5qPupPt/view?usp=sharing
> 
> ```
> 
> What about the original problem, where it loses waypoints?
> ```

I just released 2.8.4.6, which fixes the invalid waypoints.  Can you test with it, see if the waypoints are still being lost?

**Comment by Clayell** [comment]
2.8.4.6 isn't on CKAN for some reason by the way, had to install through releases here.

> What about the original problem, where it loses waypoints?

I wasn't able to reproduce the bug where user-created waypoints were being deleted before this release. I didn't see any problems with 2.8.4.6 either.
(2.8.4.6)
![Image](https://github.com/user-attachments/assets/e8b5f11c-b9a1-4453-a287-5abdf10bf6ec)

The KSC waypoint is still present though.

I think your fix might be slightly wrong? You did `if (w.name == "Site"  || w.name == "Sun")`, but shouldn't it be `if (w.name == "Site"  || w.celestialBody == "Sun")`, or something like that? That should remove the KSC waypoint as well, right?

**Comment by linuxgurugamer** [comment]
I'll check.  Not sure if w.celestialBody == "Sun" will do what you think

**Comment by linuxgurugamer** [comment]
Fixed

**Comment by Clayell** [comment]
![Image](https://github.com/user-attachments/assets/1142c31a-445a-4ab5-876e-deeb24b0dd6d)
Worked flawlessly in removing the KSC waypoint! In fact, you might even be able to get rid of the check for `w.name == "Site"`, since I imagine there could be a scenario where someone wants to name their waypoint "Site". All of the bugged waypoints were on the sun anyway.
